# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-InComments
version:      0.9
version_from: lib/Pod/InComments.pm
installdirs:  site
requires:
    Pod::POM:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
